#This file stores configuration options for Iris, such as the currently active shaderpack
<<<<<<< Updated upstream
#Thu Jan 01 20:20:38 BRT 2026
=======
<<<<<<< Updated upstream
#Thu Jan 01 20:20:38 BRT 2026
=======
#Fri Jan 02 01:06:13 GMT 2026
>>>>>>> Stashed changes
>>>>>>> Stashed changes
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.3
enableShaders=true
