#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 23 16:39:42 BRT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.3
enableShaders=true
