#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 29 22:42:31 BRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryUnbound_r5.7.1.zip
enableShaders=false
